trigger:
- main

pr:
- main

pool:
  vmImage: 'windows-latest'

variables:
  BuildConfiguration: 'Release'

steps:

- checkout: self

- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '9.0.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore Packages'
  inputs:
    command: 'restore'
    projects: 'SpecFlowAutomationFramework.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build Project'
  inputs:
    command: 'build'
    projects: 'SpecFlowAutomationFramework.csproj'
    arguments: '--configuration $(BuildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Run NUnit Tests'
  inputs:
    command: 'test'
    projects: 'SpecFlowAutomationFramework.csproj'
    arguments: '--configuration $(BuildConfiguration) --no-build --logger trx'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  condition: always()
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'