name: Selenium NUnit Automation

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest

    steps:

    - name: Checkout Project
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Cache NuGet Packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore Packages
      run: dotnet restore LearningNUnit.csproj

    - name: Build Project
      run: dotnet build LearningNUnit.csproj --configuration Release --no-restore

    - name: Execute Tests
      run: dotnet test LearningNUnit.csproj --configuration Release

    - name: Upload Extent Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ExtentReport
        path: Reports/*.html

    - name: Upload Screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Screenshots
        path: Reports/Screenshots

    - name: Upload Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Logs
        path: Reports/Logs